[tool.poetry]
name = "shiinobi-project"
version = "0.0.0"
description = ""
authors = ["baseplate-admin <61817579+baseplate-admin@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
selectolax = "^0.3.21"
requests-cache = "^1.2.1"
requests-ratelimiter = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
