name: CI

on: [push]

permissions:
    contents: write
    pull-requests: write

defaults:
    run:
        shell: bash
jobs:
    test:
        runs-on: ${{ matrix.os }}
        name: Python ${{ matrix.python-version }} - ${{ matrix.os }} sample
        strategy:
            matrix:
                os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
                python-version: [
                        # '3.9',
                        # '3.10',
                        # '3.11',
                        # "3.12",
                        '3.13',
                        # 'pypy-3.10'
                    ]

        continue-on-error: true

        steps:
            - uses: actions/checkout@v4


            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install python dependencies
              run: |
                  uv sync

            - name: Optional build headers
              run: sudo apt-get install python3-dev
              if: runner.os == 'Linux'

            - name: Run pyinstaller
              run: |
                  uv run poe build-cli

            - uses: actions/upload-artifact@v4
              with:
                  name: ${{ runner.os }}-${{ matrix.python-version }}-package
                  path: dist/*
                  retention-days: 90
                  compression-level: 9

    merge:
        runs-on: ubuntu-latest
        needs: [test]
        if: github.actor == 'dependabot[bot]' # Detect that the PR author is dependabot
        steps:
            - uses: actions/checkout@v4
            - name: Enable auto-merge for Dependabot PRs
              run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

